joint_limits:
  summit_xl_front_left_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 27.27   # 3 m/s = 27.27
    has_acceleration_limits: false
    max_acceleration: 27.27
    has_jerk_limits: false
    has_effort_limits: false
  
  summit_xl_front_right_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 27.27
    has_acceleration_limits: false
    max_acceleration: 27.27
    has_jerk_limits: false
    has_effort_limits: false
  
  summit_xl_back_left_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 27.27
    has_acceleration_limits: false
    max_acceleration: 27.27
    has_jerk_limits: false
    has_effort_limits: false
  
  summit_xl_back_right_wheel_joint:
    has_position_limits: false
    has_velocity_limits: true
    max_velocity: 27.27
    has_acceleration_limits: false
    max_acceleration: 27.27
    has_jerk_limits: false
    has_effort_limits: false

  
